# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'lucky_number_bingo_community_cli' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'lucky_number_bingo_community_cliTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    
    # Remove local network usage from Info.plist to avoid permission prompt
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_METRO_PORT=0'
      end
    end
  end
  
  # Copy Hermes dSYM files for crash symbolication
  post_integrate do |installer|
    begin
      hermes_path = Pod::Executable.execute_command('node', ['-p',
        'require.resolve(
          "react-native/sdks/hermes-engine/hermes-engine.podspec",
          {paths: [process.argv[1]]},
        )', __dir__]).strip
      hermes_dir = File.dirname(hermes_path)
      
      # Find dSYM files
      dsym_file_path = File.join(hermes_dir, "destroot", "Library", "Frameworks", "universal", "hermes.framework.dSYM")
      
      if File.exist?(dsym_file_path)
        # Copy to Pods directory
        destination = File.join(installer.sandbox.root, "hermes.framework.dSYM")
        FileUtils.cp_r(dsym_file_path, destination, :remove_destination => true)
        Pod::UI.puts "Copied Hermes dSYM to #{destination}".green
      end
    rescue => e
      Pod::UI.warn "Failed to copy Hermes dSYM: #{e.message}"
    end
  end
end
