# Fastfile for Lucky Number Bingo Community

default_platform(:ios)

platform :ios do
  xcodes(version: "16.2", select_for_current_build_only: true)
  desc "Download app metadata from App Store Connect"
  lane :download_metadata do |options|
    username = options[:username] || ENV["FASTLANE_USER"] || "sabrinaaridi@hotmail.com"
    
    deliver(
      username: username,
      app_identifier: "com.uaialternativa.luckydraw",
      skip_binary_upload: true,
      skip_screenshots: true,
      run_precheck_before_submit: false,
      force: true
    )
  end
  
  desc "Initialize metadata folder structure"
  lane :init_metadata do
    sh("fastlane deliver init --app_identifier com.uaialternativa.luckydraw")
  end
  
  desc "Upload app metadata to App Store Connect"
  lane :upload_metadata do |options|
    username = options[:username] || ENV["FASTLANE_USER"] || "sabrinaaridi@hotmail.com"
    
    deliver(
      username: username,
      app_identifier: "com.uaialternativa.luckydraw",
      skip_binary_upload: true,
      skip_screenshots: true,
      skip_app_version_update: true,
      force: true,
      submit_for_review: false
    )
  end
  
  desc "Translate metadata from en-US to all other languages"
  lane :translate_metadata do
    sh("python3 translate_metadata.py")
  end

  desc "Build and upload to TestFlight"
  lane :beta do
    is_ci = ENV['CI']
    setup_ci if is_ci

    if ENV['APP_STORE_CONNECT_API_KEY_KEY_ID']
      api_key = app_store_connect_api_key(
        key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
        issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
        key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"],
        in_house: false
      )
    end

    match(type: "appstore", readonly: is_ci)
    increment_build_number(xcodeproj: "lucky_number_bingo_community_cli.xcodeproj")
    build_app(
      scheme: "lucky_number_bingo_community_cli",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: { 
          "com.uaialternativa.luckydraw" => "match AppStore com.uaialternativa.luckydraw"
        }
      },
      xcargs: "-allowProvisioningUpdates"
    )
    upload_to_testflight(api_key: api_key)
  end
end
